"""Knowledge Management Agent — maintains and organises the system knowledge base."""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict

from agents.base_agent import BaseAgent
from core.redis_client import RedisCache
from core.vector_store import VectorMemory
from prompts.improvement_prompts import KNOWLEDGE_SYNTHESIS_PROMPT

logger = logging.getLogger(__name__)


class KnowledgeManagementAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="KnowledgeManagementAgent",
            department="self_improvement",
            role_description=(
                "You organise, index, and synthesise all knowledge generated by the system. "
                "You maintain the vector knowledge base and surface relevant insights "
                "to agents on demand."
            ),
            llm_temperature=0.05,
        )
        self.system_cache = RedisCache("system")
        self.vector_mem = VectorMemory("knowledge_base")

    async def run_cycle(self) -> None:
        # Process new lessons from inbox
        inbox = await self.read_inbox(limit=20)
        for msg in inbox:
            if msg.get("type") == "new_lessons":
                lessons = msg.get("metadata", {}).get("lessons", {}).get("lessons", [])
                for lesson in lessons:
                    await self._store_lesson(lesson)
        # Generate synthesis report
        lessons = await self.system_cache.get("learning:lessons") or []
        if len(lessons) >= 5:
            insights = await self._synthesise_knowledge(lessons)
            await self.global_cache.set("knowledge:latest_insights", insights)
            await self.report_to_ceo(
                subject="Knowledge Base Insights",
                content=str(insights)[:500],
                metadata={"insights": insights},
            )

    async def execute_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        task_type = task.get("type", "query")
        if task_type == "store":
            content = task.get("content", "")
            metadata = task.get("metadata", {})
            doc_id = f"km_{datetime.utcnow().timestamp()}"
            try:
                await self.vector_mem.upsert(doc_id, content, metadata)
            except Exception as exc:
                logger.warning("[KnowledgeManagement] Vector store unavailable: %s", exc)
                # Fallback to Redis
                existing = await self.system_cache.get("knowledge:fallback") or []
                existing.append({"id": doc_id, "content": content, "metadata": metadata})
                await self.system_cache.set("knowledge:fallback", existing[-100:], ttl=86400 * 30)
            return {"status": "ok", "stored": doc_id}
        if task_type == "query":
            query = task.get("query", "")
            try:
                results = await self.vector_mem.query(query, n_results=5)
            except Exception:
                results = []
            return {"status": "ok", "results": results}
        return {"status": "error", "message": "Unknown task type"}

    async def _store_lesson(self, lesson: Dict) -> None:
        content = f"{lesson.get('title', '')}: {lesson.get('description', '')}"
        doc_id = f"lesson_{datetime.utcnow().timestamp()}"
        try:
            await self.vector_mem.upsert(doc_id, content, lesson)
        except Exception as exc:
            logger.debug("[KM] Vector store unavailable, using Redis fallback: %s", exc)
            existing = await self.system_cache.get("knowledge:lessons_store") or []
            existing.append({"id": doc_id, "content": content, "metadata": lesson})
            await self.system_cache.set("knowledge:lessons_store", existing[-200:], ttl=86400 * 30)

    async def _synthesise_knowledge(self, lessons: list) -> Dict:
        top = sorted(lessons, key=lambda x: x.get("priority", 0), reverse=True)[:10]
        return await self.think_structured(
            KNOWLEDGE_SYNTHESIS_PROMPT.format(
                knowledge_count=len(lessons),
                top_lessons=str(top),
                objectives="Generate sustainable online income",
                trends="System is in early stage",
            ),
            schema={
                "insights": [
                    {"insight": "string", "implication": "string", "priority": 0}
                ],
                "strategy_changes": ["string"],
                "hypotheses_to_test": ["string"],
                "success_predictors": ["string"],
                "anti_patterns": ["string"],
            },
        )
